name: Show version
on:
  push:

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v3
      - run: node -v
      - run: npm -v
      - run: yarn -v
